name: on merging to develop

on:
   push:
     branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./develop_actions.js
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          