name: on merging to develop

on:
   push:
     branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: install packages
        run: npm install -g gulp axios @octokit/core @actions/github @actions/core
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
