name: FlexBeats App

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: 🔀 Merge Pull Request
        uses: bmsteven/merge-pr@0.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}